@startuml

autonumber

Recursion --> User : (n <= 1) return n
Recursion --> Recursion : recursionMethod(n - 1)
Recursion --> Recursion : recursionMethod(n - 2)
Recursion --> User : return n
Recursion --> User : return recursionMethod(n - 1) + recursionMethod(n - 2)

@enduml